name: api

on:
  push:
    branches: [ main ]

jobs:
  run-api:
    runs-on: self-hosted

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: npm install
        run: npm install

      - name: stop existing pm2 process
        run: npx pm2 delete api
        continue-on-error: true

      - name: run
        run: npx pm2 start index.js --name "api"