name: run

on:
  push:
    branches: [ main ]

jobs:
  run-app:
    runs-on: self-hosted

    steps:
      - name: checkout api
        uses: actions/checkout@v4
        with:
          path: api

      - name: checkout projects
        uses: actions/checkout@v4
        with:
          repository: mintblocks/projects
          ref: develop
          path: projects

      - name: install api deps
        working-directory: api
        run: npm install

      - name: install projects deps
        working-directory: projects
        run: npm ci

      - name: build projects
        working-directory: projects
        run: npm run build
        env:
          NODE_ENV: production
          ROOT: /projects/

      - name: prepare static dir
        run: |
          rm -rf api/projects
          mkdir -p api/projects
          cp -r projects/build/* api/projects/
          cp api/projects/editor.html api/projects/index.html

      - name: start
        working-directory: api
        run: |
          npx pm2 delete api || true
          npx pm2 start index.js --name "api"